# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    groups:
      pantos-dependencies:
        # All the pantos team libraries should be updated for patches
        patterns:
          - "pantos-*"
        update-types:
          - "minor"
          - "patch"
      other-dependencies:
        # For other dependencies we only look for minor-major updates
        exclude-patterns:
          - "pantos-*"
        update-types:
          - "minor"
          - "major"
  - package-ecosystem: "docker"
    directory: "/" # Location of Docker manifest
    schedule:
      interval: "daily"

        
